Lobby
iScsc/PotatOnline pull request #35
Opened 2023-11-29 20:14 UTC by ZynoXelek

Add the lobby and game phases to the game.
Players can chose a Team to play in, set ready and launch the game.
The seekers can then kill the hidders by hitting them. The dead players can then spectate the whole game.

Still need to implement a real end and other enhancing stuff.

2023-12-01 13:24 UTC, Shisohka approved these changes
Well done

2023-12-01 22:20 UTC, BlueNZ requested changes
Made some change to resolve conflicts, should be tested to ensure it works

2023-12-04 09:14 UTC, BlueNZ submitted a review, later dismissed

2023-12-06 17:52 UTC, BlueNZ approved these changes
Wow so much change (unironic)!

2023-12-06 17:52 UTC, merged